#!/bin/bash
echo "\033[1mRemoving unnecessary shared library files from build.\033[0m"
rm -f dist/Omission/_bz2.so
rm -f dist/Omission/_codecs_cn.so
rm -f dist/Omission/_codecs_hk.so
rm -f dist/Omission/_codecs_iso2022.so
rm -f dist/Omission/_codecs_jp.so
rm -f dist/Omission/_codecs_kr.so
rm -f dist/Omission/_codecs_tw.so
rm -f dist/Omission/_csv.so
rm -f dist/Omission/_decimal.so
rm -f dist/Omission/_hashlib.so
rm -f dist/Omission/_json.so
rm -f dist/Omission/libasound.so.2
rm -f dist/Omission/libasyncns.so.0
rm -f dist/Omission/libbsd.so.0
rm -f dist/Omission/libbz2.so.1.0
rm -f dist/Omission/libcrypto.so.1.0.0
rm -f dist/Omission/libdbus-1.so.3
rm -f dist/Omission/libdrm.so.2
rm -f dist/Omission/libexpat.so.1
rm -f dist/Omission/libfluidsynth.so.1
rm -f dist/Omission/libfreetype.so.6
rm -f dist/Omission/libgcc_s.so.1
rm -f dist/Omission/libgcrypt.so.20
rm -f dist/Omission/libglapi.so.0
rm -f dist/Omission/libgmodule-2.0.so.0
rm -f dist/Omission/libgpg-error.so.0
rm -f dist/Omission/libjack.so.0
rm -f dist/Omission/libjbig.so.0
rm -f dist/Omission/libjpeg.so.8
rm -f dist/Omission/liblz4.so.1
rm -f dist/Omission/liblzma.so.5
rm -f dist/Omission/libmad.so.0
rm -f dist/Omission/libmodplug.so.1
rm -f dist/Omission/libmpdec.so.2
rm -f dist/Omission/libmtdev.so.1
rm -f dist/Omission/libogg.so.0
rm -f dist/Omission/libpcre.so.3
rm -f dist/Omission/libpng16.so.16
rm -f dist/Omission/libpulsecommon-10.0.so
rm -f dist/Omission/libpulse-simple.so.0
rm -f dist/Omission/libpulse.so.0
rm -f dist/Omission/libreadline.so.7
rm -f dist/Omission/libSDL2-2.0.so.0
rm -f dist/Omission/libSDL2_image-2.0.so.0
rm -f dist/Omission/libSDL2_mixer-2.0.so.0
rm -f dist/Omission/libSDL2_ttf-2.0.so.0
rm -f dist/Omission/libselinux.so.1
rm -f dist/Omission/libsndfile.so.1
rm -f dist/Omission/libsndio.so.6.1
rm -f dist/Omission/libssl.so.1.0.0
rm -f dist/Omission/libsystemd.so.0
rm -f dist/Omission/libtiff.so.5
rm -f dist/Omission/libtinfo.so.5
rm -f dist/Omission/libwayland-client.so.0
rm -f dist/Omission/libwayland-cursor.so.0
rm -f dist/Omission/libwayland-egl.so.1
rm -f dist/Omission/libwebp.so.6
rm -f dist/Omission/libwrap.so.0
rm -f dist/Omission/libX11.so.6
rm -f dist/Omission/libX11-xcb.so.1
rm -f dist/Omission/libXau.so.6
rm -f dist/Omission/libxcb-glx.so.0
rm -f dist/Omission/libxcb-present.so.0
rm -f dist/Omission/libxcb-sync.so.1
rm -f dist/Omission/libXcursor.so.1
rm -f dist/Omission/libXdamage.so.1
rm -f dist/Omission/libXdmcp.so.6
rm -f dist/Omission/libXext.so.6
rm -f dist/Omission/libXfixes.so.3
rm -f dist/Omission/libXinerama.so.1
rm -f dist/Omission/libXi.so.6
rm -f dist/Omission/libxkbcommon.so.0
rm -f dist/Omission/libXrandr.so.2
rm -f dist/Omission/libXrender.so.1
rm -f dist/Omission/libxshmfence.so.1
rm -f dist/Omission/libXss.so.1
rm -f dist/Omission/libXxf86vm.so.1
rm -f dist/Omission/libz.so.1
rm -f dist/Omission/_lzma.so
rm -f dist/Omission/mmap.so
rm -f dist/Omission/_multibytecodec.so
rm -f dist/Omission/_multiprocessing.so
rm -f dist/Omission/_opcode.so
rm -f dist/Omission/readline.so
rm -f dist/Omission/resource.so
rm -f dist/Omission/_ssl.so
rm -f dist/Omission/termios.so
